# Generated by Django 5.0.14 on 2026-09-03 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Componente')),
                ('descripcion', models.TextField(verbose_name='Descripcion tecnica')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio ($)')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria (Ej: GPU, RAM, Placa Madre)')),
            ],
        ),
    ]
